[build-system]
requires = ["setuptools>=46.1.0"]

[tool.black]
line-length = 110
target-version = ['py38']
include = '\.py$'
exclude = '''
formatCompetitionData.py
'''

[tool.isort]
profile = "black"
